spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  thymeleaf:
    cache: true

whatsapp:
  verify-token: ${WHATSAPP_VERIFY_TOKEN}
  access-token: ${WHATSAPP_ACCESS_TOKEN}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID}

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  callback-url: ${RAZORPAY_CALLBACK_URL}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
